require:
  - rubocop-performance
  - rubocop-rspec

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
