language: ruby
rvm:
  - 3.1.0
  - 2.7.1
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - truffleruby-head
branches:
  only:
    - master
bundler_args: --without development
script: bundle exec rspec -fdoc
gemfile: Gemfile.travis
before_install: gem install bundler
